#!/bin/bash
set -e

export APACHE_ROOT=${APACHE_ROOT-/var/www/html/public}
export APACHE_AUTH_BASIC=${APACHE_AUTH-0}
export APACHE_AUTH_NAME=${APACHE_AUTH_NAME-"Secured Environment"}
export APACHE_AUTH_FILE=${APACHE_AUTH_FILE-/var/www/html/.htpasswd}

if [ -n "$APACHE_UID" ]; then
    usermod -u $APACHE_UID www-data
fi

if [ -n "$APACHE_GID" ]; then
    groupmod -g $APACHE_GID www-data
fi

if [[ -f '/usr/local/bin/docker-configure' ]]; then
    bash /usr/local/bin/docker-configure
fi

if [[ $OPS_PHP_XDEBUG != "1" ]]; then
    rm /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
fi

exec "$@"
