services:
  postgres16:
    image: "postgres:16.3"
    environment:
        PGDATA: "/var/lib/postgresql/data/pgdata"
        POSTGRES_HOST_AUTH_METHOD: 'trust'
    networks:
      - backend
    labels:
      - "ops.project=ops"
    ports:
      - "127.0.0.1:5433:5433"
    volumes:
      - "postgres16:/var/lib/postgresql/data/pgdata:delegated"
