version: '3'

services:
  postgres:
    image: "postgres:12.2"
    environment:
        PGDATA: "/var/lib/postgresql/data/pgdata"
        POSTGRES_HOST_AUTH_METHOD: 'trust'
    networks:
      - backend
    labels:
      - "ops.project=ops"
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - "postgres:/var/lib/postgresql/data/pgdata"
