FROM alpine:3.7

MAINTAINER Imarc <info@imarc.com>

RUN apk add --no-cache \
        bash \
        curl \
        git \
        jq \
        openssh \
        openssl \
        rsync \
        netcat-openbsd \
        unzip \
        wget

